baseURL = "https://ignasia.netlify.app"
languageCode = "en-us"
title = "Ignasia Consulting"
theme = ""

[params]
  description = "Audit, Consulting & Business Process Optimisation"
  author = "Ignasia Consulting"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 30
  [[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 40
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 50
  [[menu.main]]
    name = "Social Impact"
    url = "/social-impact/"
    weight = 60
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 70